color_bg="#191724" # Base
color_fg="#e0def4" # Text
color_green="#31748f" # Pine
color_yellow="#f6c177" # Gold
color_red="#eb6f92" # Love
color_blue="#9ccfd8" # Foam
color_cyan="#ebbcba" # Rose
color_purple="#c4a7e7" # Iris
color_gray="#6e6a86" # Muted
color_buffer="#908caa" # Subtle
color_selection="#403d52" # Highlight Med

source "$tmux_conf_dir/skin_shared.conf"
